accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login , logout ,password_reset,password_reset_done ,password_reset_confirm ,password_reset_complete

urlpatterns = [
    url(r'^$',views.home),
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name='login'),
    url(r'^profile/$',views.view_profile,name='view_profile'),
    url(r'^profile/edit$',views.edit_profile,name='edit_profile'),
    url(r'^change-password$',views.change_password,name='change_password'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
    url(r'^register/$',views.register,name='register'),

    url(r'^reset-password/$',password_reset,{'template_name':'accounts/reset_password.html',
                                             'post_reset_redirect':'accounts:password_reset_done',
                                             'email_template_name':'accounts/reset_password_email.html'},name='reset_password'),

    url(r'^reset-password/done$',password_reset_done,{'template_name':'accounts/reset_password_done.html'},name='password_reset_done'),


    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset-password/complete$',password_reset_complete,name='password_reset_complete'),
    ]

tutorial/urls.py
from django.conf import settings
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.contrib import admin

from tutorial import views as tutorial_views

urlpatterns = [
    url(r'^$', tutorial_views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls',namespace='accounts'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=1000, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect ,reverse
from accounts.form import RegistrationForm , EditProfile
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home(request):
    numbers=[1,2,3,4,5]
    name='Shobhit Pandey'
    args={'myName':name,'numbers':numbers}
    return render(request,'accounts/home.html',args)


@login_required
def view_profile(request):
    args={'user':request.user}
    return render(request,'accounts/profile.html',args)



def about(request):
    return render(request,'accounts/about.html')

def contact(request):
    return render(request,'accounts/contact.html')



def register(request):
    if (request.method=='POST'):
        form=RegistrationForm(request.POST)
        if (form.is_valid()):
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request,'accounts/register.html',args)


@login_required
def edit_profile(request):
    if request.method=='POST':
        form=EditProfile(request.POST,instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form=EditProfile(instance=request.user)
        args={'form':form}
        return render(request,'accounts/edit_profile.html',args)

@login_required
def change_password(request):
    if request.method=='POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form=PasswordChangeForm(user=request.user)
        args={'form':form}
        return render(request,'accounts/change_password.html',args)

tutorial/views.py
from django.shortcuts import redirect
from django.shortcuts import reverse

def login_redirect(request):
    return redirect(reverse('accounts:login'))

accounts/templates/accounts/about.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>ABOUT</title>
    {% endblock %}
</head>
<body>
{% block body %}
Developers of this site is Shobhit.He is pursing Btech CS from IIIT Vadodara.
{% endblock %}
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Change Password</title>
    {% endblock %}
</head>
<body>
    {% block body %}
        change password for
        {{ user  }}
        <div class="jumbotron">
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Change Password</button>
            </form>
        </div>
    {% endblock %}
</body>
</html>

accounts/templates/accounts/contact.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Contact</title>
     {% endblock %}
</head>
<body>
    {% block body %}
    Email - Shobhitpandey8@gmail.com
    {% endblock %}
</body>
</html>

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Edit Profile</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    <div class="jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    </div>
    {% endblock %}
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Home</title>
    {% endblock %}
</head>
<body>
{% block body %}

    <h1>HOME</h1>
{% endblock %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Login</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">
    {% endblock %}
</head>
<body>
{% block body %}
    <div class="jumbotron">
        <h1>Welcome</h1>
        <p>
            You can Login here!!!
        </p>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
                <button class ="btn btn-danger" type="submit" name ="button">Login</button>


        </form>

    </div>
{% endblock %}
</body>
</html>

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Logout</title>
    {% endblock%}
</head>
<body>
    {% block body %}
        <br>
        <p>
        You are logged out
        </p>
    {% endblock%}
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Profile</title>
    {% endblock %}
</head>
<body>
{% block body %}
   You have successfully logged in!!!
     <br>
     <br>
     <p>
        your profile pic is
        <img src="{{ user.userprofile.image.url }}" height="150px" width="150px">
    </p>
    <p>
        your first name is
        {{ user.first_name }}
    </p>
     <br>
    <p>
        your last name is
        {{ user.last_name }}
    </p>
     <br>
    <p>
        your email is
        {{ user.email }}
    </p>
     <br>
     <p>
        your username is
        {{ user.userprofile }}
    </p>
     <br>
     <p>
        your mobile no. is
        {{ user.userprofile.phone }}
    </p>
     <br>
     <p>
        Discription is
        {{ user.userprofile.description }}
    </p>
    <br>
     <p>
        your city is
        {{ user.userprofile.city }}
    </p>
    <br>


{% endblock %}
</body>
</html>

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block head %}
    <title>Register</title>
{% endblock %}
{% block body %}
    <h1>
    Register yourself !!!</h1>
    <br>
    <div class="jumbotron">

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

    </div>

{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Reset Password</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">
    {% endblock %}
</head>
<body>
{% block body %}
    <div class="jumbotron">
        <h1>Password Reset</h1>
        <p>
            Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
                <button class ="btn btn-danger" type="submit" name ="button">Reset My Password</button>


        </form>

    </div>
{% endblock %}
</body>
</html>

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}
    {% block head %}
    <meta charset="UTF-8">
    <title>Password reset sent</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">
    {% endblock %}
{% block body %}
    <div class="jumbotron">
        <h1>Password reset sent</h1>
        <p>
            We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
        </p>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block head %}
    <title>BASE</title>
    {% endblock %}
</head>
<body>
<br>
 <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/accounts">Shobhit</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
              {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
             <li><a href={% url 'accounts:about' %}>About</a></li>
              <li><a href={% url 'accounts:contact' %}>Contact</a></li>
                <li><a href={% url 'accounts:logout' %}>logout</a></li>
                <li><a href={% url 'accounts:view_profile' %}>Profile</a></li>
                <li><a href={% url 'accounts:edit_profile' %}>Edit Profile</a></li>
                <li><a href={% url 'accounts:change_password' %}>change Password</a></li>
                <li><a href={% url 'accounts:reset_password' %}>Forget Password?</a></li>
            </ul>
                {% else %}
               <ul class="nav navbar-nav">
             <li><a href={% url 'accounts:about' %}>About</a></li>
              <li><a href={% url 'accounts:contact' %}>Contact</a></li>

                 <li><a href={% url 'accounts:reset_password' %}>Forget Password?</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href={% url 'accounts:login' %}>Login</a></li>
                <li><a href={% url 'accounts:register' %}>Register</a></li>

            </ul>
              {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
<br>
    {% block body %}
        <h1>
        Base
        </h1>
    {% endblock %}
</body>
</html>